version: "3.8"
services:
  flaskapp: # This is where we can assign a hostname
    container_name: flaskapp_container
    build:
      context: .
    ports:
      - "35000:5000"
    depends_on:
      - minio
      - postgres
    networks:
      - app-network

  minio:
    container_name: minio_container
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network

  postgres:
    container_name: postgres_container
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  minio_data:
  postgres_data:
  
networks:
  app-network:
    driver: bridge
